import type { Customer, Product } from "@/types";

type ProductSeed = {
  id: string;
  model: string;
  colourCode: string;
  size: string;
  name: string;
  category: string;
  fineCategory: string;
  description: string;
  color: string;
  price: number;
  markup: number;
  composition: Product["composition"];
  stock: number;
  lowStockThreshold: number;
  weight: string;
  measurements: Partial<Record<"lengthA" | "lengthB" | "lengthC" | "lengthD" | "lengthE" | "lengthF" | "lengthG" | "lengthH", string>>;
};

const productSeeds: ProductSeed[] = [
  {
    id: "demo-product-101",
    model: "P101",
    colourCode: "CAM",
    size: "S",
    name: "Milan Wool Long Coat",
    category: "Coats & Jackets",
    fineCategory: "Long Coat",
    description: "Double-faced wool long coat with clean lapel and relaxed fit.",
    color: "Camel",
    price: 68.5,
    markup: 1.2,
    composition: [{ material: "Wool", percentage: 70 }, { material: "Polyester", percentage: 25 }, { material: "Elastane", percentage: 5 }],
    stock: 18,
    lowStockThreshold: 4,
    weight: "950",
    measurements: { lengthA: "112", lengthB: "41", lengthC: "52", lengthD: "60", lengthE: "14", lengthF: "58", lengthG: "50", lengthH: "24" },
  },
  {
    id: "demo-product-102",
    model: "P102",
    colourCode: "BLK",
    size: "M",
    name: "Oslo Quilted Short Jacket",
    category: "Coats & Jackets",
    fineCategory: "Short Coat",
    description: "Light padded jacket with snap closure and curved hem.",
    color: "Black",
    price: 42,
    markup: 1.1,
    composition: [{ material: "Nylon", percentage: 60 }, { material: "Polyester", percentage: 40 }],
    stock: 24,
    lowStockThreshold: 5,
    weight: "950",
    measurements: { lengthA: "62", lengthB: "44", lengthC: "55", lengthD: "59", lengthE: "13", lengthF: "54", lengthG: "49", lengthH: "25" },
  },
  {
    id: "demo-product-103",
    model: "P103",
    colourCode: "WHT",
    size: "M",
    name: "Luna Ribbed T-Shirt",
    category: "Tops",
    fineCategory: "T-Shirt",
    description: "Soft ribbed cotton T-shirt with stretch and slim silhouette.",
    color: "White",
    price: 9.8,
    markup: 1.4,
    composition: [{ material: "Cotton", percentage: 92 }, { material: "Elastane", percentage: 8 }],
    stock: 80,
    lowStockThreshold: 12,
    weight: "420",
    measurements: { lengthA: "58", lengthB: "36", lengthC: "42", lengthD: "18", lengthE: "42" },
  },
  {
    id: "demo-product-104",
    model: "P104",
    colourCode: "GRN",
    size: "S",
    name: "Siena Satin Midi Dress",
    category: "Dresses",
    fineCategory: "Dress",
    description: "Satin midi dress with draped waist and soft A-line hem.",
    color: "Sage Green",
    price: 31.5,
    markup: 1.3,
    composition: [{ material: "Viscose", percentage: 55 }, { material: "Polyester", percentage: 45 }],
    stock: 16,
    lowStockThreshold: 3,
    weight: "420",
    measurements: { lengthA: "118", lengthB: "37", lengthC: "44", lengthD: "36", lengthE: "48", lengthG: "74" },
  },
  {
    id: "demo-product-105",
    model: "P105",
    colourCode: "NVY",
    size: "L",
    name: "Paris Wide Leg Pants",
    category: "Trousers & Jeans",
    fineCategory: "Long Pants",
    description: "High-waist wide-leg pants with pleated front and fluid drape.",
    color: "Navy",
    price: 24.9,
    markup: 1.25,
    composition: [{ material: "Polyester", percentage: 78 }, { material: "Viscose", percentage: 18 }, { material: "Elastane", percentage: 4 }],
    stock: 35,
    lowStockThreshold: 6,
    weight: "420",
    measurements: { lengthA: "38", lengthB: "52", lengthC: "104", lengthD: "76", lengthE: "32", lengthF: "28" },
  },
  {
    id: "demo-product-106",
    model: "P106",
    colourCode: "BEI",
    size: "M",
    name: "Florence Linen Shirt",
    category: "Tops",
    fineCategory: "T-Shirt",
    description: "Breathable linen blend short sleeve top with relaxed neckline.",
    color: "Beige",
    price: 17.2,
    markup: 1.15,
    composition: [{ material: "Linen", percentage: 65 }, { material: "Cotton", percentage: 35 }],
    stock: 42,
    lowStockThreshold: 7,
    weight: "420",
    measurements: { lengthA: "61", lengthB: "39", lengthC: "49", lengthD: "21", lengthE: "50" },
  },
  {
    id: "demo-product-107",
    model: "P107",
    colourCode: "BRN",
    size: "M",
    name: "Berlin Faux Leather Jacket",
    category: "Coats & Jackets",
    fineCategory: "Short Coat",
    description: "Structured faux leather jacket with metal zipper and fitted cuff.",
    color: "Chocolate",
    price: 49.9,
    markup: 1.2,
    composition: [{ material: "Polyurethane", percentage: 55 }, { material: "Polyester", percentage: 45 }],
    stock: 20,
    lowStockThreshold: 4,
    weight: "950",
    measurements: { lengthA: "58", lengthB: "43", lengthC: "51", lengthD: "61", lengthE: "12", lengthF: "50", lengthG: "45", lengthH: "24" },
  },
  {
    id: "demo-product-108",
    model: "P108",
    colourCode: "RED",
    size: "M",
    name: "Valencia Knit Dress",
    category: "Dresses",
    fineCategory: "Dress",
    description: "Stretch knit dress with clean square neckline and midi length.",
    color: "Wine Red",
    price: 28.4,
    markup: 1.35,
    composition: [{ material: "Viscose", percentage: 50 }, { material: "Nylon", percentage: 30 }, { material: "Elastane", percentage: 20 }],
    stock: 22,
    lowStockThreshold: 5,
    weight: "420",
    measurements: { lengthA: "110", lengthB: "35", lengthC: "41", lengthD: "34", lengthE: "45", lengthF: "57", lengthG: "66" },
  },
  {
    id: "demo-product-109",
    model: "P109",
    colourCode: "KHK",
    size: "S",
    name: "Tokyo Cargo Pants",
    category: "Trousers & Jeans",
    fineCategory: "Long Pants",
    description: "Utility cargo pants with adjustable ankle tabs and side pockets.",
    color: "Khaki",
    price: 27.6,
    markup: 1.18,
    composition: [{ material: "Cotton", percentage: 72 }, { material: "Polyester", percentage: 25 }, { material: "Elastane", percentage: 3 }],
    stock: 30,
    lowStockThreshold: 6,
    weight: "420",
    measurements: { lengthA: "35", lengthB: "49", lengthC: "101", lengthD: "74", lengthE: "31", lengthF: "21" },
  },
  {
    id: "demo-product-110",
    model: "P110",
    colourCode: "STN",
    size: "L",
    name: "Copenhagen Trench Coat",
    category: "Coats & Jackets",
    fineCategory: "Long Coat",
    description: "Classic belted trench coat with storm flap and button front.",
    color: "Stone",
    price: 57.8,
    markup: 1.2,
    composition: [{ material: "Cotton", percentage: 58 }, { material: "Polyester", percentage: 42 }],
    stock: 14,
    lowStockThreshold: 3,
    weight: "950",
    measurements: { lengthA: "116", lengthB: "43", lengthC: "55", lengthD: "62", lengthE: "14", lengthF: "61", lengthG: "52", lengthH: "25" },
  },
];

export const DEMO_PRODUCTS: Array<Omit<Product, "createdAt">> = productSeeds.map((product) => ({
  id: product.id,
  barcode: product.model,
  sku: `${product.model}${product.colourCode}${product.size}`,
  name: product.name,
  category: product.category,
  fineCategory: product.fineCategory,
  category2: "Demo",
  category3: "Sample",
  description: product.description,
  size: product.size,
  color: product.color,
  price: product.price,
  cost: 0,
  b2cMarkup: product.markup,
  b2cPrice: Math.round(product.price * (1 + product.markup) * 100) / 100,
  composition: product.composition,
  stock: product.stock,
  lowStockThreshold: product.lowStockThreshold,
  otherSku: `EXT-${product.model}`,
  weight: product.weight,
  ...product.measurements,
}));

export const DEMO_CUSTOMERS: Array<Omit<Customer, "createdAt">> = [
  {
    id: "demo-customer-001",
    clientType: "B2B",
    name: "Isabel",
    surname: "Martin",
    businessType: "ESP EMPRESA",
    businessName: "Moda Norte SL",
    email: "orders@modanorte.es",
    vatNumber: "B12345678",
    phoneCountryCode: "+34",
    phoneNumber: "600 101 001",
    phone: "+34 600 101 001",
    fiscalAddress: { line1: "Calle Serrano 18", postalCode: "28001", provinceState: "Madrid", country: "Spain" },
    logisticsAddress: { line1: "Calle Alcala 120", postalCode: "28009", provinceState: "Madrid", country: "Spain" },
    address: "Calle Serrano 18, Madrid",
    taxRate: 21,
  },
  {
    id: "demo-customer-002",
    clientType: "B2B",
    name: "Marco",
    surname: "Rossi",
    businessType: "EU VAT",
    businessName: "Rossi Boutique SRL",
    email: "buying@rossiboutique.it",
    vatNumber: "IT12345678901",
    phoneCountryCode: "+39",
    phoneNumber: "02 5550 2010",
    phone: "+39 02 5550 2010",
    fiscalAddress: { line1: "Via Torino 34", postalCode: "20123", provinceState: "Milano", country: "Italy" },
    logisticsAddress: { line1: "Via Tortona 12", postalCode: "20144", provinceState: "Milano", country: "Italy" },
    address: "Via Torino 34, Milano",
    taxRate: 0,
  },
  {
    id: "demo-customer-003",
    clientType: "B2C",
    name: "Laura",
    surname: "Garcia",
    email: "laura.garcia@example.com",
    phoneCountryCode: "+34",
    phoneNumber: "611 202 002",
    phone: "+34 611 202 002",
    fiscalAddress: { line1: "Avinguda Diagonal 410", postalCode: "08037", provinceState: "Barcelona", country: "Spain" },
    logisticsAddress: { line1: "Avinguda Diagonal 410", postalCode: "08037", provinceState: "Barcelona", country: "Spain" },
    address: "Avinguda Diagonal 410, Barcelona",
    taxRate: 21,
  },
  {
    id: "demo-customer-004",
    clientType: "B2B",
    name: "Claire",
    surname: "Dubois",
    businessType: "EU VAT",
    businessName: "Maison Claire SARL",
    email: "contact@maisonclaire.fr",
    vatNumber: "FR12345678912",
    phoneCountryCode: "+33",
    phoneNumber: "1 45 20 18 88",
    phone: "+33 1 45 20 18 88",
    fiscalAddress: { line1: "14 Rue Saint-Honore", postalCode: "75001", provinceState: "Paris", country: "France" },
    logisticsAddress: { line1: "22 Rue Reaumur", postalCode: "75003", provinceState: "Paris", country: "France" },
    address: "14 Rue Saint-Honore, Paris",
    taxRate: 0,
  },
  {
    id: "demo-customer-005",
    clientType: "B2C",
    name: "Sofia",
    surname: "Lopez",
    email: "sofia.lopez@example.com",
    phoneCountryCode: "+34",
    phoneNumber: "622 303 003",
    phone: "+34 622 303 003",
    fiscalAddress: { line1: "Calle Colon 9", postalCode: "46004", provinceState: "Valencia", country: "Spain" },
    logisticsAddress: { line1: "Calle Colon 9", postalCode: "46004", provinceState: "Valencia", country: "Spain" },
    address: "Calle Colon 9, Valencia",
    taxRate: 21,
  },
  {
    id: "demo-customer-006",
    clientType: "B2B",
    name: "Anna",
    surname: "Schmidt",
    businessType: "EU VAT",
    businessName: "Schmidt Mode GmbH",
    email: "purchase@schmidtmode.de",
    vatNumber: "DE123456789",
    phoneCountryCode: "+49",
    phoneNumber: "30 5557 9001",
    phone: "+49 30 5557 9001",
    fiscalAddress: { line1: "Friedrichstrasse 90", postalCode: "10117", provinceState: "Berlin", country: "Germany" },
    logisticsAddress: { line1: "Oranienburger Strasse 20", postalCode: "10178", provinceState: "Berlin", country: "Germany" },
    address: "Friedrichstrasse 90, Berlin",
    taxRate: 0,
  },
  {
    id: "demo-customer-007",
    clientType: "B2B",
    name: "Elena",
    surname: "Ruiz",
    businessType: "ESP AUTONOMO",
    businessName: "Elena Ruiz Fashion",
    email: "elena@eruizfashion.es",
    vatNumber: "ES12345678Z",
    phoneCountryCode: "+34",
    phoneNumber: "633 404 004",
    phone: "+34 633 404 004",
    fiscalAddress: { line1: "Calle Larios 6", postalCode: "29005", provinceState: "Malaga", country: "Spain" },
    logisticsAddress: { line1: "Poligono Guadalhorce Nave 8", postalCode: "29004", provinceState: "Malaga", country: "Spain" },
    address: "Calle Larios 6, Malaga",
    taxRate: 21,
  },
  {
    id: "demo-customer-008",
    clientType: "B2C",
    name: "Marta",
    surname: "Navarro",
    email: "marta.navarro@example.com",
    phoneCountryCode: "+34",
    phoneNumber: "644 505 005",
    phone: "+34 644 505 005",
    fiscalAddress: { line1: "Paseo Independencia 21", postalCode: "50001", provinceState: "Zaragoza", country: "Spain" },
    logisticsAddress: { line1: "Paseo Independencia 21", postalCode: "50001", provinceState: "Zaragoza", country: "Spain" },
    address: "Paseo Independencia 21, Zaragoza",
    taxRate: 21,
  },
  {
    id: "demo-customer-009",
    clientType: "B2B",
    name: "Nadia",
    surname: "Khan",
    businessType: "INTERNATIONAL",
    businessName: "Khan Concept Store",
    email: "nadia@khanconcept.co.uk",
    vatNumber: "GB987654321",
    phoneCountryCode: "+44",
    phoneNumber: "20 7000 9090",
    phone: "+44 20 7000 9090",
    fiscalAddress: { line1: "31 Carnaby Street", postalCode: "W1F 7DL", provinceState: "London", country: "United Kingdom" },
    logisticsAddress: { line1: "8 Commercial Street", postalCode: "E1 6LP", provinceState: "London", country: "United Kingdom" },
    address: "31 Carnaby Street, London",
    taxRate: 0,
  },
  {
    id: "demo-customer-010",
    clientType: "B2C",
    name: "Carmen",
    surname: "Ortega",
    email: "carmen.ortega@example.com",
    phoneCountryCode: "+34",
    phoneNumber: "655 606 006",
    phone: "+34 655 606 006",
    fiscalAddress: { line1: "Calle Sierpes 15", postalCode: "41004", provinceState: "Sevilla", country: "Spain" },
    logisticsAddress: { line1: "Calle Sierpes 15", postalCode: "41004", provinceState: "Sevilla", country: "Spain" },
    address: "Calle Sierpes 15, Sevilla",
    taxRate: 21,
  },
];
