SET search_path = cms, public;

INSERT INTO measurement_templates (
  fine_category,
  measurement_code,
  measurement_name,
  unit,
  is_required,
  sort_order,
  ui_label,
  notes
) VALUES
  ('Long Coat', 'A', 'Total Length', 'cm', true, 1, 'Length A - Total Length', 'From shoulder/high point to hem.'),
  ('Long Coat', 'B', 'Shoulder Width', 'cm', true, 2, 'Length B - Shoulder Width', 'Shoulder seam to shoulder seam.'),
  ('Long Coat', 'C', 'Chest Width', 'cm', true, 3, 'Length C - Chest Width', 'Flat garment chest width.'),
  ('Long Coat', 'D', 'Sleeve Length', 'cm', true, 4, 'Length D - Sleeve Length', 'From shoulder seam to cuff.'),
  ('Long Coat', 'E', 'Cuff Width', 'cm', true, 5, 'Length E - Cuff Width', 'Flat cuff opening.'),
  ('Long Coat', 'F', 'Hem Width', 'cm', true, 6, 'Length F - Hem Width', 'Flat bottom width.'),
  ('Long Coat', 'G', 'Waist Width', 'cm', true, 7, 'Length G - Waist Width', 'Flat waist width.'),
  ('Long Coat', 'H', 'Armhole', 'cm', true, 8, 'Length H - Armhole', 'Armhole curve/height.'),
  ('Short Coat', 'A', 'Total Length', 'cm', true, 1, 'Length A - Total Length', null),
  ('Short Coat', 'B', 'Shoulder Width', 'cm', true, 2, 'Length B - Shoulder Width', null),
  ('Short Coat', 'C', 'Chest Width', 'cm', true, 3, 'Length C - Chest Width', null),
  ('Short Coat', 'D', 'Sleeve Length', 'cm', true, 4, 'Length D - Sleeve Length', null),
  ('Short Coat', 'E', 'Cuff Width', 'cm', true, 5, 'Length E - Cuff Width', null),
  ('Short Coat', 'F', 'Hem Width', 'cm', true, 6, 'Length F - Hem Width', null),
  ('Short Coat', 'G', 'Waist Width', 'cm', false, 7, 'Length G - Waist Width', 'Optional if style is straight.'),
  ('Short Coat', 'H', 'Armhole', 'cm', true, 8, 'Length H - Armhole', null),
  ('T-Shirt', 'A', 'Body Length', 'cm', true, 1, 'Length A - Body Length', null),
  ('T-Shirt', 'B', 'Shoulder Width', 'cm', true, 2, 'Length B - Shoulder Width', null),
  ('T-Shirt', 'C', 'Chest Width', 'cm', true, 3, 'Length C - Chest Width', null),
  ('T-Shirt', 'D', 'Sleeve Length', 'cm', true, 4, 'Length D - Sleeve Length', null),
  ('T-Shirt', 'E', 'Hem Width', 'cm', true, 5, 'Length E - Hem Width', null),
  ('Dress', 'A', 'Total Length', 'cm', true, 1, 'Length A - Total Length', null),
  ('Dress', 'B', 'Shoulder Width', 'cm', false, 2, 'Length B - Shoulder Width', 'Optional for sleeveless dress.'),
  ('Dress', 'C', 'Chest Width', 'cm', true, 3, 'Length C - Chest Width', null),
  ('Dress', 'D', 'Waist Width', 'cm', true, 4, 'Length D - Waist Width', null),
  ('Dress', 'E', 'Hip Width', 'cm', true, 5, 'Length E - Hip Width', null),
  ('Dress', 'F', 'Sleeve Length', 'cm', false, 6, 'Length F - Sleeve Length', 'Optional for sleeveless dress.'),
  ('Dress', 'G', 'Hem Width', 'cm', true, 7, 'Length G - Hem Width', null),
  ('Long Pants', 'A', 'Waist Width', 'cm', true, 1, 'Length A - Waist Width', null),
  ('Long Pants', 'B', 'Hip Width', 'cm', true, 2, 'Length B - Hip Width', null),
  ('Long Pants', 'C', 'Outseam Length', 'cm', true, 3, 'Length C - Outseam Length', null),
  ('Long Pants', 'D', 'Inseam Length', 'cm', true, 4, 'Length D - Inseam Length', null),
  ('Long Pants', 'E', 'Thigh Width', 'cm', true, 5, 'Length E - Thigh Width', null),
  ('Long Pants', 'F', 'Leg Opening', 'cm', true, 6, 'Length F - Leg Opening', null)
ON CONFLICT (fine_category, measurement_code) DO UPDATE SET
  measurement_name = EXCLUDED.measurement_name,
  unit = EXCLUDED.unit,
  is_required = EXCLUDED.is_required,
  sort_order = EXCLUDED.sort_order,
  ui_label = EXCLUDED.ui_label,
  notes = EXCLUDED.notes;
